### ISSUE TITLE
财会通识第8章 第三题的答案 ，选择D是不是更合适 ？

### ISSUE THREAD

**Issue by cjd9023** [FinTechCourse2019/Answers#3]
大神，第3题的答案，在哪能看出来，选择D是不是更合适，综合资本成本

**Comment by FinTechCourse2019** [comment]
第九章，只有2题啊，都是选择题
第三题是 ？

财会我弱鸡，希望财会专业的同学弄一下

**Comment by cjd9023** [comment]
我弄错了，是第8章的

**Comment by cjd9023** [comment]
以为这是官方的github

**Comment by FinTechCourse2019** [comment]
纯民间行为

**Comment by FinTechCourse2019** [comment]
@cjd9023 
wechat上ping我一下，
我分配一下权限给你
我们一起讨论怎么把github弄好，
既方便自己的学习，同时也给大家方便

**Comment by FinTechCourse2019** [comment]
这题，我也不确定，我直接问问于老师

**Comment by cjd9023** [comment]
知道的时间晚了，培训名额满了，没参加培训，只报名考试自购教材学习；
wechat id： cjd9023， 加下好友；

**Comment by FinTechCourse2019** [comment]
我是说呢，群里广播都没人应答
于老师，游老师，都还没有回复我，
等待中……

**Comment by FinTechCourse2019** [comment]
于老师，已经回复
综合（加权）资本成本最低时，
资本结构最优，企业价值最大
